version: "3.8"
services:
  pragmatic_live_feed_aggregator:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    env_file:
      - .env
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    restart: always
    env_file:
      - .env
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    volumes:
      - cache:/data

networks:
  redis:
    driver: bridge

volumes:
  cache:
    driver: local
