// Code generated by MockGen. DO NOT EDIT.
// Source: internal/pragmaticlivefeed/repo.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	dto "github.com/dsha256/pragmatic-live-feed-aggregator/pkg/dto"
	gomock "github.com/golang/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// AddTable mocks base method.
func (m *MockRepository) AddTable(ctx context.Context, table dto.PragmaticTable) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddTable", ctx, table)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddTable indicates an expected call of AddTable.
func (mr *MockRepositoryMockRecorder) AddTable(ctx, table interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddTable", reflect.TypeOf((*MockRepository)(nil).AddTable), ctx, table)
}

// GetTableByTableAndCurrencyIDs mocks base method.
func (m *MockRepository) GetTableByTableAndCurrencyIDs(ctx context.Context, tableID, currencyID string) (dto.PragmaticTable, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTableByTableAndCurrencyIDs", ctx, tableID, currencyID)
	ret0, _ := ret[0].(dto.PragmaticTable)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTableByTableAndCurrencyIDs indicates an expected call of GetTableByTableAndCurrencyIDs.
func (mr *MockRepositoryMockRecorder) GetTableByTableAndCurrencyIDs(ctx, tableID, currencyID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTableByTableAndCurrencyIDs", reflect.TypeOf((*MockRepository)(nil).GetTableByTableAndCurrencyIDs), ctx, tableID, currencyID)
}

// ListTables mocks base method.
func (m *MockRepository) ListTables(ctx context.Context) ([]dto.PragmaticTableWithID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTables", ctx)
	ret0, _ := ret[0].([]dto.PragmaticTableWithID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTables indicates an expected call of ListTables.
func (mr *MockRepositoryMockRecorder) ListTables(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTables", reflect.TypeOf((*MockRepository)(nil).ListTables), ctx)
}

// MockAggregateRepository is a mock of AggregateRepository interface.
type MockAggregateRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAggregateRepositoryMockRecorder
}

// MockAggregateRepositoryMockRecorder is the mock recorder for MockAggregateRepository.
type MockAggregateRepositoryMockRecorder struct {
	mock *MockAggregateRepository
}

// NewMockAggregateRepository creates a new mock instance.
func NewMockAggregateRepository(ctrl *gomock.Controller) *MockAggregateRepository {
	mock := &MockAggregateRepository{ctrl: ctrl}
	mock.recorder = &MockAggregateRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAggregateRepository) EXPECT() *MockAggregateRepositoryMockRecorder {
	return m.recorder
}

// AddTable mocks base method.
func (m *MockAggregateRepository) AddTable(ctx context.Context, table dto.PragmaticTable) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddTable", ctx, table)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddTable indicates an expected call of AddTable.
func (mr *MockAggregateRepositoryMockRecorder) AddTable(ctx, table interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddTable", reflect.TypeOf((*MockAggregateRepository)(nil).AddTable), ctx, table)
}

// GetTableByTableAndCurrencyIDs mocks base method.
func (m *MockAggregateRepository) GetTableByTableAndCurrencyIDs(ctx context.Context, tableID, currencyID string) (dto.PragmaticTable, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTableByTableAndCurrencyIDs", ctx, tableID, currencyID)
	ret0, _ := ret[0].(dto.PragmaticTable)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTableByTableAndCurrencyIDs indicates an expected call of GetTableByTableAndCurrencyIDs.
func (mr *MockAggregateRepositoryMockRecorder) GetTableByTableAndCurrencyIDs(ctx, tableID, currencyID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTableByTableAndCurrencyIDs", reflect.TypeOf((*MockAggregateRepository)(nil).GetTableByTableAndCurrencyIDs), ctx, tableID, currencyID)
}

// ListTables mocks base method.
func (m *MockAggregateRepository) ListTables(ctx context.Context) ([]dto.PragmaticTableWithID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTables", ctx)
	ret0, _ := ret[0].([]dto.PragmaticTableWithID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTables indicates an expected call of ListTables.
func (mr *MockAggregateRepositoryMockRecorder) ListTables(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTables", reflect.TypeOf((*MockAggregateRepository)(nil).ListTables), ctx)
}
